$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: odsc-transferlearning-pytorch
version: 1
image: mcr.microsoft.com/azureml/curated/pytorch-1.10-ubuntu18.04-py38-cuda11-gpu:36
description: Training enviroment PyTorch 1.10 / CUDA 11 / GPU
